config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'        
  }

  resources :users do
    resources :stores, only: [:index, :new, :create, :edit, :update]   
  end  
   
  get "/search_stores",          to: "pages#search_stores",           as: "search_stores"
  get "/stores_error_show",      to: "pages#error_show"
  get "/user_type/sign_up",      to: "pages#select_user_type"
  root "pages#index"

  resources :stores do
    resources :store_sub_pages do
      collection do
        get :show_gmap
        get :show_menu
        get :show_album
        get :show_comments       
      end 
    end
    
    resources  :store_pictures, only: [:destroy, :show] do
      collection do
        get  :edit
        post :update
      end
    end

    resource :menus, only: [:edit, :update]

  end

  scope :controller => "pages", :path => "/comments", :as => "comment" do
    get "new/:store_id"     => :new_comment,       :as => "new"
    get "create/:store_id"  => :create_comment,    :as => "create"
    get "user_list"         => :user_list_comments,:as => "by_user_list"
  end
              
end

app/views/shared/frontend/_filter_search_options.html.erb
</br>
</br>
</br>
</br>

<article class="panel is-warning">
  <p class="panel-heading">
    篩選項目
  </p>

  <label class="panel-block">
  <p>預算區間:</p>
  </label>  

  <%= form_tag( "/search_stores" , method: "get") do %>
    <label class="panel-block">
    <%= number_field_tag 'filter_price_from_keyword', @filter_kw_price_from_temp, min: 1, max: 1000, step: 1 %>
    &nbsp;~&nbsp;
    <%= number_field_tag 'filter_price_to_keyword',   @filter_kw_price_to_temp, min: 1, max: 1000, step: 1 %>
    </label>

    <%= text_field_tag :geo_keyword, @geo_kw_temp, class:"input is-hidden" %>  
    <%= text_field_tag :feat_keyword, @feat_kw_temp, class:"input is-hidden" %> 
    <%= text_field_tag :order_keyword, @order_kw_temp, class:"input is-hidden" %> 

    <div class="panel-block">
    <%= submit_tag "重新篩選結果", class:"button is-outlined is-fullwidth" %>
    </div>
  <% end %>
</article>

app/views/shared/frontend/_main_search_bar.html.erb
<%= form_tag("/search_stores", method: "get") do %>
<div data-controller="main-page-event" class="field has-addons columns is-gapless main_search_bar" >
    <div class="control column">
        <%= text_field_tag :geo_keyword, @geo_kw_temp, class:"input", id:"serch_input_01", data:{action:"click->main-page-event#showDashBar01"}, placeholder:"區域、街道名" %>
        <div   id="serch_dashBar_01" class=""></div>
    </div> 
    <div class="control column"> 
        <%= text_field_tag :feat_keyword, @feat_kw_temp, class:"input", id:"serch_input_02", data:{action:"click->main-page-event#showDashBar02"}, placeholder:"店名、特色" %>
        <div   id="serch_dashBar_02" class=""></div>
    </div>
    <div class="control">
        <%= image_submit_tag("baseline_search.png", class:"button is-warning") %>
    </div>
</div>
<% end %>
</br>







  
  

app/views/shared/frontend/_message.html.erb
<article class="message is-warning">
  <div class="message-body">

    <%= render 'shared/frontend/message/identity'%>
    <%= render 'shared/frontend/message/relation_info'%>

    <% if notice %>      
      <strong>提醒:&nbsp;<%= notice %></strong>
    <% end %>

    <% if alert %>
      <strong>錯誤:&nbsp;<%= alert %></strong>
    <% end %>

  </div>
</article>

    

app/views/shared/frontend/_navbar.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <%= link_to image_tag("logo.png", style: 'height:28;'), root_path, class:'navbar-item' %>
    <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
    </div>

    <div class="navbar-end">        
        <% if user_signed_in? %>
          <% if current_user.user_type == 'customer' %>
            <div class="navbar-item has-dropdown is-hoverable">
                <a class="navbar-link">
                  <%= avatar(current_user, size:50)%>
                  <%= current_user.email %>
                </a>
                <div class="navbar-dropdown">
                  <%= link_to "編輯帳號資料", edit_user_registration_path, class: 'navbar-item', method: 'GET' %>            
                  <%= link_to "顯示評論列表", comment_by_user_list_path,      class: 'navbar-item', method: 'GET' %>
                  <hr class="navbar-divider">
                  <%= link_to "登出", destroy_user_session_path, class: 'navbar-item', method: 'DELETE',
                      data: {confirm: '確定是否登出?'} %>    
                </div>
            </div>
          <% elsif current_user.user_type == 'manager' %>
            <div class="navbar-item has-dropdown is-hoverable">
                <a class="navbar-link">
                  <%= avatar(current_user, size:50)%>
                  <%= current_user.email %>
                </a>
                <div class="navbar-dropdown">
                  <%= link_to "編輯帳號資料", edit_user_registration_path, class: 'navbar-item', method: 'GET' %>            
                  <%= link_to "顯示評論列表", comment_by_user_list_path,      class: 'navbar-item', method: 'GET' %>
                  <hr class="navbar-divider">
                  <% if user_session["has_store?"] == false %>
                    <%= link_to "新增店家資料", new_user_store_path(user_id:current_user.id),          class: 'navbar-item', method: 'GET' %>
                  <% else %>
                    <%= link_to "顯示店家主頁", user_stores_path(user_id:current_user.id),             class: 'navbar-item', method: 'GET' %>
                    <%= link_to "編輯店家資料", edit_user_store_path(user_id:current_user.id, id:current_user.store.id), class: 'navbar-item', method: 'GET' %>
                    <%= link_to "編輯菜單資料", edit_store_menus_path(current_user.store.id),          class: 'navbar-item', method: 'GET' %>
                    <%= link_to "編輯相簿資料", edit_store_store_pictures_path(current_user.store.id), class: 'navbar-item', method: 'GET' %>
                  <% end %>
                  <hr class="navbar-divider">
                  <%= link_to "登出", destroy_user_session_path, class: 'navbar-item', method: 'DELETE',
                      data: {confirm: '確定是否登出?'} %>    
                </div>
            </div>            
          <% end %>
        <% else %>
        <div class="navbar-item">
        <div class="buttons">
            <%= link_to "註冊",  user_type_sign_up_path, class: 'button is-warning', method: 'GET' %>
            <%= link_to "登入", new_user_session_path,      class: 'button is-light',   method: 'GET' %>            
        </div>
        </div>
        <% end %>  
    
    </div>
  </div>
</nav>

<div class="ribbon-bar">
</div>

app/views/shared/frontend/_order_search_list.html.erb
<p>排序方式：</p>
</br>
<div class="tabs is-boxed">
  <ul>
    <% if @order_kw_temp == "avg_score" %>
      <li class="is-active">
    <% else %>
      <li class="">
    <% end %>
        <span>
        <%= link_to "評價分數", search_stores_path(geo_keyword:@geo_kw_temp, feat_keyword:@feat_kw_temp,
                                                  order_keyword:"avg_score", filter_price_from_keyword:@filter_kw_price_from_temp,
                                                  filter_price_to_keyword:@filter_kw_price_to_temp ) %>
        </span>
    </li>

    <% if @order_kw_temp == "comments_count" %>  
      <li class="is-active">
    <% else %>
      <li class="">
    <% end %>
        <span>
        <%= link_to "評論數目", search_stores_path(geo_keyword:@geo_kw_temp, feat_keyword:@feat_kw_temp,
                                                  order_keyword:"comments_count", filter_price_from_keyword:@filter_kw_price_from_temp,
                                                  filter_price_to_keyword:@filter_kw_price_to_temp ) %>        
        </span>
    </li>

    <% if @order_kw_temp == "updated_at" %> 
      <li class="is-active">
    <% else %>
      <li class="">
    <% end %>
        <span>
        <%= link_to "更新日期", search_stores_path(geo_keyword:@geo_kw_temp, feat_keyword:@feat_kw_temp,
                                                  order_keyword:"updated_at", filter_price_from_keyword:@filter_kw_price_from_temp,
                                                  filter_price_to_keyword:@filter_kw_price_to_temp ) %>          
        </span>
    </li>

  </ul>
</div>

<div class="result-list-div">
<p>&nbsp;列出&nbsp;<%=@stores.count%>&nbsp;項結果</p>
<% @stores.each do |store|%>
    </br>
    <%= link_to store_path(store.id) do %>
    <div class="card">
        <header class="card-header">
          <div class="card-title-dash">
            <span class="card-header-title">
                <div class="media-content">    
                <p class="title is-4"><%= link_to store.title, store_path(store.id) %></p>
                <p class="subtitle is-6"><%=store.feature %></p>
                <p></p>
                </div>
            </span>
          </div>
        </header>

        <div class="card-content">
            <div class="media">
            <div class="media-left">
                <div class="search_list_avater">
                  <%= avatar(store.user, size:150)%>
                </div>
            </div>

            <div class="media-content">

              <div class="star-ratings-css">
              <div class="star-ratings-css-top" style="width:<%= store.avg_score*20.0 %>%"><span>★</span><span>★</span><span>★</span><span>★</span><span>★</span></div>
              <div class="star-ratings-css-bottom"><span>★</span><span>★</span><span>★</span><span>★</span><span>★</span></div>
              </div>

              <p class="is-6">評分:&nbsp; <%= format("%.2f",store.avg_score) %>&nbsp;[<%=store.comments_count %>則評價]</p>
              <p class="is-6">預算:&nbsp;約 NT$<%=store.budget %></p>
              </br>
              <p class="is-6">地址:&nbsp;<%= store.city %><%= store.district %><%= store.address %></p>
            </div>
              
            </div>
        </div>
    </div>
    <% end %>
    <div class="ribbon-table-line"></div>    
<% end %>
</div>