config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'        
  }

  resources :users do
    resources :stores, only: [:index, :new, :create, :edit, :update]   
  end  
   
  get "/search_stores",          to: "pages#search_stores",           as: "search_stores"
  get "/stores_error_show",      to: "pages#error_show"
  get "/user_type/sign_up",      to: "pages#select_user_type"
  root "pages#index"

  resources :stores do
    resources :store_sub_pages do
      collection do
        get :show_gmap
        get :show_menu
        get :show_album
        get :show_comments       
      end 
    end
    
    resources  :store_pictures, only: [:destroy, :show] do
      collection do
        get  :edit
        post :update
      end
    end

    resource :menus, only: [:edit, :update]

  end

  scope :controller => "pages", :path => "/comments", :as => "comment" do
    get "new/:store_id"     => :new_comment,       :as => "new"
    get "create/:store_id"  => :create_comment,    :as => "create"
    get "user_list"         => :user_list_comments,:as => "by_user_list"
  end
              
end

app/controllers/store_pictures_controller.rb
class StorePicturesController < ApplicationController
    before_action :authenticate_user!, except: [:show]

    def edit
        @store     = current_user.store    
    end

    def update
        respond_to do |format|
            @store = current_user.store
            if @store.store_images.attach(update_store_pictures_params[:store_images])
              format.html { redirect_to update_store_pictures_path(store_id:@store.id) }
              format.json {
                # 遵循慣例參數為陣列，但 DirectUpload 一次只會負責一張圖片
                image = ActiveStorage::Blob.find_signed(update_store_pictures_params[:store_images].first)
                # 從後端取的圖片（resize）的網址
                image_url = Rails.application.routes.url_helpers.rails_representation_url(image.variant(resize: "200x200"), only_path: true)
                render json: { status: :ok, url: image_url, id: image.id, file_name: image.filename, file_size: image.byte_size }
              }
            else
              format.html { redirect_to update_store_pictures_path(store_id:@store.id) }
              format.json { render json: @store.errors, status: :unprocessable_entity }
            end
        end    
    end
    
    def destroy
        image_id = params[:id].to_i
        @store = current_user.store
        # 有時有無法刪除的問題    
        # @store.store_images.find_by(id:image_id).purge
        ActiveStorage::Attachment.find(image_id).purge
        render json: { status: :ok }    
    end    
    
    def show
        respond_to do |format|
            image_id  = params[:id]
            store_id  = params[:store_id]
            image     = Store.find(store_id).store_images.find(image_id)       
            image_url = rails_blob_url(image)
            format.json { render json: {image_url: image_url, status: :ok} }
            end    
    end    


    private
    def update_store_pictures_params
        params.require(:store).permit( store_images: [])
    end 

end    

app/views/store_pictures/edit.html.erb
<h2 class="title" >相簿內容編輯</h2>
</br>

<article class="message is-warning">
  <div class="message-body">   
      <strong>提醒:&nbsp;</strong>
      <div id="upload_message"></div>
  </div>
</article>

</br>
<div data-controller="store-images-direct-upload"
     data-uploads-direct-upload-url= <%= rails_direct_uploads_path %>
     info-store-id = <%= @store.id %>
     id="update_info_div">
    <div class="file">
    <label class="file-label">    
    <input type="file" class="file-input" name="store_images" multiple="true" data-action="change->store-images-direct-upload#start" direct_upload="true" id="store_images_input">
    <span class="file-cta">
        <span class="file-label">
        選擇待上傳檔案
        </span>
    </span>
    </label>
    </div>

    </br>
    <span class="tag is-large is-warning">
    <h6 class="title is-6">已上傳圖片清單</h6>
    </span>
    <div class="ribbon-table-line">
    </div>
    </br>

        <div id="store_images_preview_region">
            <% @store.store_images.each do |store_image| %>  
                <div class="img-wrapper">       
                <%= image_tag store_image.variant(resize: '200x200') %>
                <%= link_to '刪除', store_store_picture_path(@store.id, store_image.id), data:{action:"click->store-images-direct-upload#destroy"} %>       
                </div>
            <% end %>   
        </div>   
      

</div>