config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'        
  }

  resources :users do
    resources :stores, only: [:index, :new, :create, :edit, :update]   
  end  
   
  get "/search_stores",          to: "pages#search_stores",           as: "search_stores"
  get "/stores_error_show",      to: "pages#error_show"
  get "/user_type/sign_up",      to: "pages#select_user_type"
  root "pages#index"

  resources :stores do
    resources :store_sub_pages do
      collection do
        get :show_gmap
        get :show_menu
        get :show_album
        get :show_comments       
      end 
    end
    
    resources  :store_pictures, only: [:destroy, :show] do
      collection do
        get  :edit
        post :update
      end
    end

    resource :menus, only: [:edit, :update]

  end

  scope :controller => "pages", :path => "/comments", :as => "comment" do
    get "new/:store_id"     => :new_comment,       :as => "new"
    get "create/:store_id"  => :create_comment,    :as => "create"
    get "user_list"         => :user_list_comments,:as => "by_user_list"
  end
              
end

app/views/pages/edit_comment.html.erb
<h1>編輯評價內容頁面</h1>

app/views/pages/edit_menus.html.erb
<h2 class="title" >編輯&nbsp;<%= current_user.store.title%>&nbsp;的菜單內容</h2>

</br> 

<%= form_for( @store, url: "/update_menus/#{current_user.store.id}", method: "get") do |f| %>
    <%= text_field_tag :menus_status, @menus_status, class:"input is-hidden" %>

    <div class="field columns is-vcentered"> 
        <div class="control column">
            <span class="tag is-large is-warning">
            <h6 class="subtitle is-5">品項</h6>
            </span>
        </div>

        <div class="control column">
            <span class="tag is-large is-warning">
            <h6 class="subtitle is-5">價格</h6>
            </span>
        </div>

        <div class="control column">
        </div>      
    </div>

    
    <div id='menus'>
        <%= f.fields_for :menus do |menu| %>
            <%= render 'menu_fields', f: menu %>
        <% end %>     
        <div class='links'>
            <p>
            </br>
            <%= link_to_add_association "新增一組條目 「料理-價格」", f, :menus %> 
            </p>
        </div>
    </div>

    </br>
    <%= link_to "取消", :back , class:"button is-light" %>
    <%= f.submit "提交資料", class:"button is-warning" %>

    

    
<% end %>

app/views/pages/error_show.html.erb
<h2 class="title" >抱歉，找不到該店家資料</h2>
</br>
<div class="" style="margin:0px auto;">
    <%= image_tag("search_error.png", :style => "display:block; margin:auto;") %>
</div>

app/views/pages/index.html.erb
<%= render 'shared/frontend/main_search_bar'%>
<%= render 'shared/frontend/message'%>

</br>
<div class="ribbon-table-line"></div>
</br>

app/views/pages/new_comment.html.erb
<h2 class="title" >填寫新評論</h2>
<p class="help" >*為必填欄位</p>

<% if !user_session["form_error_message"].nil? %>
    <article class="message is-warning">
    <div class="message-body">
        <%= user_session["form_error_message"] %>
    </div>
    </article>
<% end %>

</br>
撰寫一則關於&nbsp;<%= @store.title %>&nbsp;的評論
</br>

<%= form_for(@comment, url: comment_create_path(store_id:@store.id), method: :get ) do |form| %>
    </br>
    <span class="tag is-large is-warning">
    <h6 class="title is-6">評論內容</h6>
    </span>
    <div class="ribbon-table-line">
    </div>
    </br>

    <div class="field">
        <%= form.label :score, "評價分數*", class: "label" %>
        <div class="control">
            <div class="select">
                <%= form.select :score, options_for_select(["1","2","3","4","5"])  %>
            </div>
        </div>
    </div>

    <div class="field">
        <%= form.label :visit_time, "消費日期*", class: "label" %>
        <div class="control">
            <%= form.text_field :visit_time, class: "input", id:"theCutePicker" %>
        </div>
    </div>

    <div class="field">
        <%= form.label :spend, "消費金額*", class: "label" %>
        <div class="control">
            <%= form.text_field :spend, class: "input" %>
        </div>
    </div>

    <div class="field">
        <%= form.label :content, "感想*", class: "label" %>
        <div class="control">
            <%= form.text_area :content, class: "textarea" %>
        </div>
    </div>

    <div class="field">
        <div class="control">
            <%= form.text_field :store_id, class: "input is-hidden", value: @store.id %>
        </div>
    </div>


    <div class="field">
        <%= form.submit "提交資料", class: "button is-warning "%>
    </div>
    <%= link_to "取消", root_path, class: 'button is-light', method: 'GET' %> 

<% end %>

app/views/pages/search_stores.html.erb
<%= render 'shared/frontend/main_search_bar'%>
<%= render 'shared/frontend/message'%>

</br>
<div class="ribbon-table-line"></div>
</br>

<div class="columns">
    <div class="column">
        <%= render 'shared/frontend/filter_search_options'%>
    </div>
    <div class="column is-three-quarters">
        <%= render 'shared/frontend/order_search_list'%>
    </div>
</div>

app/views/pages/select_user_type.html.erb
<h1 class="title" >選擇使用者註冊類別</h1>


<div class="columns">
<div class="column">
    <div class="card">
    <figure class="image">
    <%= link_to image_tag("ramen_boy.png",
     style:'width: auto;
	        height: auto;
	        max-width: 100%;
	        max-height: 100%;'),  new_user_registration_path(user_type: 'customer'), class: 'card-image', method: 'GET' %>
    </figure>
    </div>  
</div>
<div class="column">
    <div class="card">
    <figure class="image">
    <%= link_to image_tag("ramen_boss.png",
     style:'width: auto;
	        height: auto;
	        max-width: 100%;
	        max-height: 100%;'),  new_user_registration_path(user_type: 'manager'), class: 'card-image', method: 'GET' %> 
    </figure>
    </div> 
</div>
</div>

app/views/pages/show_gmap.html.erb
<div id="ajax_output">
    <div class="title">顯示 Google Map</div>

    <p>
        <div id="map" class="Google_map"></div>
    </p>

    <div id="mapLat" style="display:none" ><%= @latitude  %></div>
    <div id="mapLng" style="display:none" ><%= @longitude %></div>
</div>

<% provide :head_tags do %>
    <meta name='turbolinks-visit-control' content='reload'>
    <script>
    function initMap(lat, lng) {   
      var myCoords = new google.maps.LatLng(lat, lng);
      var mapOptions = {
      center: myCoords,
      zoom: 14
      }; 
      var map = new google.maps.Map(document.getElementById('map'), mapOptions);
      var marker = new google.maps.Marker({
      position: myCoords,
      map: map
      });
    }
      
    document.addEventListener("DOMContentLoaded", function(){        
        initMap(<%=@latitude%>, <%=@longitude%>)
    });
    </script>
<% end %>

app/views/pages/show_store.html.erb
<h2 class="title" >店家資料主頁-外部查詢結果</h2>

<nav class="breadcrumb has-arrow-separator" aria-label="breadcrumbs">
  <ul>
    地理位置：
    <li><%= link_to @store.city,     search_stores_path(geo_keyword:@store.city) %></li>
    <li><%= link_to @store.district, search_stores_path(geo_keyword:@store.district) %></li>
  </ul>
</nav>

</br>
<div class="ribbon-table-line"></div>
</br>

<div class="card">
  <div class="card-image">
      <%= image_tag("ramen_bar.png") %>  
  </div>

  <div class="ribbon-table-line"></div>  

  <div class="card-content">

    <div class="media">
      <div class="media-left">
        <figure class="image">
          <%= avatar(@store.user,size:90) %>
        </figure>
      </div>
      <div class="media-content">
        <p class="title is-4">
        <%= @store.title %>
        </p>
        <p class="subtitle is-6">
        <%= @store.avg_score %>
        </p>
        <p class="subtitle is-6">
        <%= @store.city %><%= @store.district %><%= @store.address %>       
        </p>
      </div>

      <% if  current_user.present? && current_user.id!= @store.user.id%>
        <%= link_to "發表評論",  comment_new_path( user_id:current_user.id, store_id:@store.id ), class: 'button is-warning', method: 'GET' %>         
      <% end %>  
    </div>

    <div class="content">
    <%= @store.promote %>
    </br>
    特色:  <%= @store.feature %>
    </div>
  </div>
</div>

<div class="ribbon-table-line"></div>

<div class="card">
  <header class="card-header">
    <p class="card-header-title">
    簡介:
    </br>
    <%= @store.intro %>
    </p>
  </header>
  <div class="card-content">
    <div class="content">
    <p class="title is-6">
    其他資料:
    </p>
    </br>
    營業時間:<%= @store.opening_hours %>
    </br>
    公休日:<%= @store.closed_day %>
    </br>
    預算:<%= @store.budget %> 
    </br>
    備註:<%= @store.memo %> 
    </br> 
    </div>
  </div>

  <div data-controller = "substore-content-loader"
      data-substore-content-loader-map-url      ="/show_gmap?full_address=<%= @store.city %><%= @store.district %><%= @store.address %>"
      data-substore-content-loader-comments-url ="/comments/store_list/<%= @store.id %>"
      data-substore-content-loader-menu-url ="/show_menu/<%= @store.id %>"
   data-substore-content-loader-album-url    ="/show_album/<%= @store.id %>" >

    <footer class="card-footer">
      <a data-action="click->substore-content-loader#showComments" id="comments_trigger" class="card-footer-item">評價</a>
      <a data-action="click->substore-content-loader#showMenu" id="menu_trigger" class="card-footer-item">菜單</a>
      <a data-action="click->substore-content-loader#showAlbum" id="album_trigger" class="card-footer-item">相簿</a>
      <a data-action="click->substore-content-loader#showMap" id="gmap_trigger" class="card-footer-item">地圖</a>
    </footer>
    <div class="ribbon-bar">
    </div>

    <div id="output" class="sub_page_output" >
    </div>  

  </div>

</div>

<div id="mapLat" class="is-hidden" ><%= @latitude  %></div>
<div id="mapLng" class="is-hidden" ><%= @longitude %></div>


<script>
$(function(){

  $(".sub_page_output").on("mouseover", ".image_hide", function() {    
    first_image_id  = $("#first_image_id").val();
    last_image_id   = $("#last_image_id").val();
    image_id        = $(this).attr("image_id");
    image_frame     = $(this).parent(".image_hihe_frame");
    store_id        = $("#store_id").val();
    request_url     = "/find_store_picture_url/"+store_id+"/"+image_id;

    if(image_id == first_image_id){
      pre_image_id  = last_image_id;
      next_image_id = $(this).parents(".column").next(".column").find(".image_hide").attr("image_id");    
    }else if(image_id == last_image_id){
      pre_image_id  = $(this).parents(".column").prev(".column").find(".image_hide").attr("image_id");
      next_image_id = first_image_id;
    }else{
      pre_image_id  = $(this).parents(".column").prev(".column").find(".image_hide").attr("image_id");
      next_image_id = $(this).parents(".column").next(".column").find(".image_hide").attr("image_id");
    }

    $("#pre_link_button").attr("pre_link_img_id", pre_image_id);
    $("#next_link_button").attr("next_link_img_id", next_image_id);
    drawFrameBorder(image_frame);
  
    $.ajax({
         type: "POST",
          url: request_url,
     dataType: "json",
      success: function(data){
        $("#focus_image").attr("src",data.image_url);  
      }  
    })
  });


  $(".sub_page_output").on("click", "#pre_link_button", function() {
    target_id  = $(this).attr("pre_link_img_id");
    select_str = ".image_hide[image_id='"+target_id+"']"
    $(select_str).mouseover();

  })

  $(".sub_page_output").on("click", "#next_link_button", function() {
    target_id = $(this).attr("next_link_img_id");
    select_str = ".image_hide[image_id='"+target_id+"']"
    $(select_str).mouseover();
  })

  function drawFrameBorder(image_frame) {
    $(".image_hihe_frame").attr("class", "image_hihe_frame fade_img_unchose");
    image_frame.attr("class", "image_hihe_frame frame_chose fade_img_chose");
  }

});
</script>

app/views/pages/user_list_comments.html.erb
<h2 class="title" ><%= current_user.username%>&nbsp;所發表過的評價清單列表</h2>
</br>
<% if @comments_exist %>
<% @comments.each do |comment|%>
    <div class="card">
            <div class="card-content">
                <div class="comment-head">                
                <div class="media">
                    <div class="media-left">
                        <% if comment.user.avatar.attached? %>
                            <%= avatar(comment.user, size:60)%>
                        <% else %>
                            <%= image_tag("no_picture.png", size:"60x60", class: "user-avatar") %>
                        <% end %>    
                    </div>

                    <div class="media-content">
                        <p class="is-4"><%=comment.user.username %>&nbsp;comment on&nbsp;<%=comment.store.title%></p>
                            <div class="star-ratings-css">
                            <div class="star-ratings-css-top" style="width:<%= comment.score*20.0 %>%"><span>★</span><span>★</span><span>★</span><span>★</span><span>★</span></div>
                            <div class="star-ratings-css-bottom"><span>★</span><span>★</span><span>★</span><span>★</span><span>★</span></div>
                            </div>
                        <p>消費金額:&nbsp;<%=comment.spend %></p>
                        <p>於&nbsp;<%=comment.visit_time %>訪問，已訪問<%=comment.visit_count %>次</p>
                        <hr>
                        <div class="comment-content">
                        評論內容:
                        </br>
                        <%=comment.content %>
                        </br>
                        <div class="comment_time">
                        <time class=""><%=comment.user.updated_at%></time>
                        </div>
                        </div>
                    </div>    
                </div>
                </div>
            </div>
        </div>
    <div class="ribbon-table-line"></div>
<% end %>
<% else %>
    <p>目前暫無已發表評論資料</p>
<% end %>